### PR TITLE
added parser init for treesitter to nvim plugin

### LINKED ISSUE #8: Initialization code missing in nvim plugin?
Hi,

i installed the grammar and thought everything was working. Looking into the plugin, the grammar registration is missing and only the filetype handling is given. Thus, after the plugin is installed i must register the parser by hand.

Was there a reason to not include the parser_config extension?

Kind regards
Alexander

### PR DESCRIPTION
**Pull request by aserowy**
closes #8

### CODE REVIEW

**Comment by luckasRanarison** [comment]
I think we should also update the readme, and by the way does this affect the Nix configuration? I don't use nix and I wasn't the one who made it.

 (Asking because you seem to also use nix)

**Comment by aserowy** [comment]
> I think we should also update the readme, and by the way does this affect the Nix configuration? I don't use nix and I wasn't the one who made it.
> 
> (Asking because you seem to also use nix)

Hi,

i updated the readme. The nix code looks fine (i cannot test it, because my nvim config is not nixified). It should run better now, because the initialization was missing there as well.

**Comment by aserowy** [comment]
Ok, we got it :). On the downside we must seperate both configurations to be able to use two different kind of inits. The normal plugin uses the 'normal' way of registering the parser. Nix on the other hand builds the parser and query on its own and registers the build one directly.

Building the flake gives now the following output again.

```sh
󱄅 󰎑 󰉋 tree-sitter-hypr at 󰊤 on 󰘬 master !1 is 󰏗 v1.0.0 via  via 󱘗 took 2s 
11:23:28 : open result/plugin/init.lua
vim.filetype.add({
  pattern = { [".*/hypr/.*%.conf"] = "hypr" },
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = "hypr",
  callback = function(event) vim.bo[event.buf].commentstring = "# %s" end,
})

vim.treesitter.language.require_language("hypr", "/nix/store/c5sn8bqfh9spipqq6yrac4hl49ldm461-hypr-g
rammar-v1.0.2/parser")
```

**Comment by luckasRanarison** [comment]
Thanks a lot for your PR!

**Pull request merged**
